### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by simjbaum** [YaqiangCao/cLoops#10]
I get the following error after isntallation and running the test script:

[seb@pc examples]$ sh run.sh
2019-05-03 18:39:59,823 INFO Command line: cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -m 0 -eps 0 -minPts 0 -p 1 -w True -j True -s True -c  -hic False -cut 0 -plot False -max_cut False
2019-05-03 18:39:59,824 ERROR minPts not assigned!
  Converting  to .hic file which could be loaded in juicebox
juicer_tools pre -n -r 1000,5000,10000,20000 -d 0.951037801484 CTCF_chr21_juice.hic hg38
0.951037801484 does not exist or does not contain any reads.
rm 0.951037801484
Converting CTCF_chr21_juice.hic to juicer's hic file finished.
Converting  to washU track.
bedtools sort -i 0.139065929601 > CTCF_chr21_PETs_washU.txt
rm 0.139065929601
bgzip CTCF_chr21_PETs_washU.txt
tabix -p bed CTCF_chr21_PETs_washU.txt.gz
Converting CTCF_chr21_PETs_washU.txt to washU random accessed track finished.
2019-05-03 18:40:02,585 INFO Getting finger print for chiapet
Traceback (most recent call last):
  File "/pc/home/seb/no_backup/python/bin/jd2fingerprint", line 4, in <module>
    __import__('pkg_resources').run_script('cLoops==0.93', 'jd2fingerprint')
  File "/pc/home/seb/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/pc/home/seb/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(script_code, namespace, namespace)
  File "/pc/home/seb/no_backup/python/lib/python2.7/site-packages/cLoops-0.93-py2.7.egg/EGG-INFO/scripts/jd2fingerprint", line 118, in <module>

  File "/pc/home/seb/no_backup/python/lib/python2.7/site-packages/cLoops-0.93-py2.7.egg/EGG-INFO/scripts/jd2fingerprint", line 94, in getFingerPrint

  File "/pc/home/seb/no_backup/python/lib/python2.7/site-packages/cLoops-0.93-py2.7.egg/EGG-INFO/scripts/jd2fingerprint", line 70, in jds2FingerPrint

ValueError: need at least one array to concatenate

**Comment by YaqiangCao** [comment]
Dear User,
        The run.sh has been updated, and please use the new first command
line as following:
cLoops -f GSM1872886_GM12878_CTCF_ChIA-PET_chr21_hg38.bedpe.gz -o chiapet -w
-j -s -m 1
-m 1 is added as in latest version.
Sorry for the trouble.
