### ISSUE TITLE
ERROR: no inter-ligation PETs detected for eps 5000 minPts 50,can't model the distance cutoff,continue anyway

### ISSUE THREAD

**Issue by ysora** [YaqiangCao/cLoops#24]
I am trying to run cLoops with a public data (Vian et al., 2018) but it gives error as below: 

```
cooler dump --join GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30.mcool::resolutions/5000 -o GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.bedpe

cLoops -f GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.bedpe -o GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.cLoops -j -m 3
```

2020-11-12 15:19:44,166 INFO Command line: cLoops -f GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.bedpe -o GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.cLoops -m 3 -eps 0 -minPts 0 -p 1 -w False -j True -s False -c  -hic False -cut 0 -plot False -max_cut False
2020-11-12 15:19:44,166 INFO mode:3	 eps:[5000, 7500, 10000]	 minPts:[50, 40, 30, 20]	 hic:1	
2020-11-12 15:19:44,178 INFO Parsing PETs from GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.bedpe, requiring initial distance cutoff > 0
632800000 PETs processed from GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.bedpe()
2020-11-12 18:27:59,059 INFO Totaly 632884895 PETs from GSE82144_Kieffer-Kwon-2017-activated_B_cells_72_hours_WT_30_res5kb.bedpe, in which 0 cis PETs
2020-11-12 18:27:59,180 INFO ERROR: no inter-ligation PETs detected for eps 5000 minPts 50,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,180 INFO ERROR: no inter-ligation PETs detected for eps 5000 minPts 40,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,181 INFO ERROR: no inter-ligation PETs detected for eps 5000 minPts 30,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,181 INFO ERROR: no inter-ligation PETs detected for eps 5000 minPts 20,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,181 INFO ERROR: no inter-ligation PETs detected for eps 7500 minPts 50,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,181 INFO ERROR: no inter-ligation PETs detected for eps 7500 minPts 40,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,181 INFO ERROR: no inter-ligation PETs detected for eps 7500 minPts 30,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,181 INFO ERROR: no inter-ligation PETs detected for eps 7500 minPts 20,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,182 INFO ERROR: no inter-ligation PETs detected for eps 10000 minPts 50,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,182 INFO ERROR: no inter-ligation PETs detected for eps 10000 minPts 40,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,183 INFO ERROR: no inter-ligation PETs detected for eps 10000 minPts 30,can't model the distance cutoff,continue anyway
2020-11-12 18:27:59,183 INFO ERROR: no inter-ligation PETs detected for eps 10000 minPts 20,can't model the distance cutoff,continue anyway
Traceback (most recent call last):
  File "/mnt/data0/apps/anaconda/Anaconda2-5.2/bin/cLoops", line 11, in <module>
    load_entry_point('cLoops==0.93', 'console_scripts', 'cLoops')()
  File "build/bdist.linux-x86_64/egg/cLoops/pipe.py", line 349, in main
  File "build/bdist.linux-x86_64/egg/cLoops/pipe.py", line 280, in pipe
  File "/mnt/data0/apps/anaconda/Anaconda2-5.2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 2618, in amin
    initial=initial)
  File "/mnt/data0/apps/anaconda/Anaconda2-5.2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity

Please let me know if there is something that I missed. Thanks.

**Comment by YaqiangCao** [comment]
Dear User,
        Could you please show me first several lines of your BEDPE file?
According to the log information, seems there is no intra-chromosomal PETs
in your file.
Best,
Yaqiang

**Comment by ysora** [comment]
It looks like this:

chr1	2995000	3000000	chr2	30065000	30070000	1
chr1	3000000	3005000	chr1	3000000	3005000	363
chr1	3000000	3005000	chr1	3005000	3010000	26
chr1	3000000	3005000	chr1	3010000	3015000	50
chr1	3000000	3005000	chr1	3015000	3020000	23
chr1	3000000	3005000	chr1	3020000	3025000	27
chr1	3000000	3005000	chr1	3025000	3030000	11
chr1	3000000	3005000	chr1	3030000	3035000	4
chr1	3000000	3005000	chr1	3035000	3040000	14
chr1	3000000	3005000	chr1	3040000	3045000	9
chr1	3000000	3005000	chr1	3045000	3050000	3
chr1	3000000	3005000	chr1	3050000	3055000	7
chr1	3000000	3005000	chr1	3055000	3060000	9
chr1	3000000	3005000	chr1	3060000	3065000	5
chr1	3000000	3005000	chr1	3065000	3070000	2
chr1	3000000	3005000	chr1	3070000	3075000	4
chr1	3000000	3005000	chr1	3075000	3080000	3
chr1	3000000	3005000	chr1	3080000	3085000	4
chr1	3000000	3005000	chr1	3085000	3090000	3
chr1	3000000	3005000	chr1	3090000	3095000	2
chr1	3000000	3005000	chr1	3095000	3100000	4
chr1	3000000	3005000	chr1	3100000	3105000	5
chr1	3000000	3005000	chr1	3105000	3110000	4
chr1	3000000	3005000	chr1	3110000	3115000	5
chr1	3000000	3005000	chr1	3115000	3120000	3
chr1	3000000	3005000	chr1	3120000	3125000	2
chr1	3000000	3005000	chr1	3125000	3130000	1
chr1	3000000	3005000	chr1	3130000	3135000	2
chr1	3000000	3005000	chr1	3135000	3140000	4
chr1	3000000	3005000	chr1	3140000	3145000	1
chr1	3000000	3005000	chr1	3145000	3150000	1
chr1	3000000	3005000	chr1	3150000	3155000	2
chr1	3000000	3005000	chr1	3155000	3160000	2
chr1	3000000	3005000	chr1	3160000	3165000	3
chr1	3000000	3005000	chr1	3165000	3170000	1
chr1	3000000	3005000	chr1	3170000	3175000	2
chr1	3000000	3005000	chr1	3175000	3180000	1
chr1	3000000	3005000	chr1	3185000	3190000	3
chr1	3000000	3005000	chr1	3190000	3195000	1
chr1	3000000	3005000	chr1	3195000	3200000	1
chr1	3000000	3005000	chr1	3200000	3205000	5
chr1	3000000	3005000	chr1	3205000	3210000	3
chr1	3000000	3005000	chr1	3210000	3215000	3
chr1	3000000	3005000	chr1	3215000	3220000	6
chr1	3000000	3005000	chr1	3220000	3225000	2
chr1	3000000	3005000	chr1	3225000	3230000	3
chr1	3000000	3005000	chr1	3235000	3240000	2
chr1	3000000	3005000	chr1	3240000	3245000	6
chr1	3000000	3005000	chr1	3245000	3250000	3
chr1	3000000	3005000	chr1	3250000	3255000	2
chr1	3000000	3005000	chr1	3255000	3260000	2
chr1	3000000	3005000	chr1	3260000	3265000	3
chr1	3000000	3005000	chr1	3270000	3275000	1
chr1	3000000	3005000	chr1	3280000	3285000	4
chr1	3000000	3005000	chr1	3285000	3290000	3
chr1	3000000	3005000	chr1	3295000	3300000	2
chr1	3000000	3005000	chr1	3300000	3305000	3
chr1	3000000	3005000	chr1	3310000	3315000	3
chr1	3000000	3005000	chr1	3315000	3320000	1
chr1	3000000	3005000	chr1	3320000	3325000	6
chr1	3000000	3005000	chr1	3325000	3330000	3
chr1	3000000	3005000	chr1	3330000	3335000	2
chr1	3000000	3005000	chr1	3340000	3345000	1
chr1	3000000	3005000	chr1	3345000	3350000	1
chr1	3000000	3005000	chr1	3350000	3355000	1
chr1	3000000	3005000	chr1	3355000	3360000	2
chr1	3000000	3005000	chr1	3360000	3365000	1
chr1	3000000	3005000	chr1	3365000	3370000	1
chr1	3000000	3005000	chr1	3375000	3380000	1
chr1	3000000	3005000	chr1	3380000	3385000	3

**Comment by ysora** [comment]
Can it be the problem of data resolution?? Here, I used 5kb data. Do you think it is too sparse to use?

**Comment by YaqiangCao** [comment]
Hi Sora,
    cLoops use raw PETs to call loops. I can not call if it is too sparse.
Additionally, each item in the line is separated by \t or space? For
cLoops, \t is used to parse each line.
Best,
Yaqiang

**Comment by ysora** [comment]
Yes, I will try with 10kb resolution data. 
The data is tab-delimited.
Thanks.

**Comment by YaqiangCao** [comment]
Could you please send me one chromosome data for test? For example chr21 of
human or chr19 of mouse.

**Comment by ysora** [comment]
You mean the .bedpe file?? Sure, I will do that.

**Comment by YaqiangCao** [comment]
Yes, the .bedpe file.

**Comment by ysora** [comment]
Yoon, Sora has shared a OneDrive for Business file with you. To view it, click the link below.
<https://pennmedicine-my.sharepoint.com/:u:/g/personal/yoons_pennmedicine_upenn_edu/EUWD-eGwtr5FrsLEynw97UYBrlikFXEqDmClwt6g_AooWQ>
[https://r1.res.office365.com/owa/prem/images/dc-zip_20.png]<https://pennmedicine-my.sharepoint.com/:u:/g/personal/yoons_pennmedicine_upenn_edu/EUWD-eGwtr5FrsLEynw97UYBrlikFXEqDmClwt6g_AooWQ>
Vian_ab_72h_res10kb_chr19.zip<https://pennmedicine-my.sharepoint.com/:u:/g/personal/yoons_pennmedicine_upenn_edu/EUWD-eGwtr5FrsLEynw97UYBrlikFXEqDmClwt6g_AooWQ>

I also had a same error with 10kb resolution data.
Here, I send you the bedpe file of chr19.
Thanks,

Sora
________________________________

**Comment by YaqiangCao** [comment]
HI Sora,
     I have problems to access the files, seems only Penn can access.
Best,
Yaqiang

**Comment by ysora** [comment]
I'd like to share it through google drive. Could you send me your email?
Thanks.

Sora
________________________________

**Comment by YaqiangCao** [comment]
my email is caoyaqiang0410@gmail.com

**Comment by ysora** [comment]
Please check the email.
Thanks

Sora
________________________________

**Comment by YaqiangCao** [comment]
Hi Sara,
    In your bedpe file, only 7 columns, meanwhile following are
required for cLoops. (https://github.com/YaqiangCao/cLoops) .
[image: image.png]
     Additionally, cLoops uses raw PETs to find loops.  Meanwhile in your
data, it seems the bins and PETs in it, by default each line from BEDPE
file cLoops will consider it as a PET, not multiple.  If you use HICPro
process the fastq files, you can use
https://github.com/YaqiangCao/cLoops/blob/master/scripts/hicpropairs2bedpe
to convert to cLoops input BEDPE file.  With your BEDPE data, I am afraid I
can not find loops.
   Could you please show me some screenshot of your chr19 with Juicebox or
other tools? If you can observe loops visually, cLoops should detect them.
Best,
Yaqiang

**Comment by ysora** [comment]
Thanks for fast responsee.
I don't have HiCPro result but only have .cool or .hic file.
Can I generate appropriate input format from those file types?
Thanks.

Sora
________________________________

**Comment by ysora** [comment]
[cid:05833d65-923d-4f8f-85a8-ad9b950a1eb1]

Yes, chr19 has clear loops like this.

[cid:816e1ffb-ace3-4135-9f4e-7cb9f98c2b37]
This is coordinate information.
Thanks.

Sora

________________________________

**Comment by YaqiangCao** [comment]
Hi Sora,
    I am not sure if Juicer or HiCExplor can export PETs level all data.
    One possible solution I guess is export with smallest resolution as
1KB, for one record chr1 xs xe chr2 ye ys 3, in the region you random
generate 3 BEDPE records. It will affect the boundaries, however, I think
will call loops. Better to start with raw PETs. Or you can just try HiCCUPS
from Juicer to call loops with the .hic files.
Best,
Yaqiang
