### ISSUE TITLE
callstripes has problems

### ISSUE THREAD

**Issue by MackZhang** [YaqiangCao/cLoops#4]
I can not set parameters except default ones. The callstripe program will report an error even the default parameter, like "-minPts 5", appear on the command line.

**Comment by MackZhang** [comment]
**callStripes -d CTCF_HiChIP -o CTCF_stripe -c chr21 -j**
2018-11-15 20:45:16,118 INFO Command line: callStripes -d CTCF_HiChIP -o CTCF_stripe -eps 20000 -minPts 5 -pets 200 -ext 50 -c ['chr21'] -p 1 -j True
Clustering chr21 and chr21 using eps as 20000, minPts as 5
Clustering chr21 and chr21 finished.
Clustering chr21 and chr21 using eps as 20000, minPts as 5
Clustering chr21 and chr21 finished.
Genomic coverage model built from CTCF_HiChIP/chr21-chr21.jd
0 interaction p-values estimated for CTCF_HiChIP/chr21-chr21.jd
Genomic coverage model built from CTCF_HiChIP/chr21-chr21.jd
0 interaction p-values estimated for CTCF_HiChIP/chr21-chr21.jd
2018-11-15 20:46:00,516 INFO callStripes finished. Bye! Used time:0:00:44.399089


**callStripes -d CTCF_HiChIP -o CTCF_stripe -c chr21 -j -minPts 5**
2018-11-15 20:46:08,362 INFO Command line: callStripes -d CTCF_HiChIP -o CTCF_stripe -eps 20000 -minPts 5 -pets 200 -ext 50 -c ['chr21'] -p 1 -j True
Clustering chr21 and chr21 using eps as 20000, minPts as 5
Clustering chr21 and chr21 finished.
Clustering chr21 and chr21 using eps as 20000, minPts as 5
Clustering chr21 and chr21 finished.
Genomic coverage model built from CTCF_HiChIP/chr21-chr21.jd

Traceback (most recent call last):
  File "/usr/local/bin/callStripes", line 5, in <module>
    pkg_resources.run_script('cLoops==0.91', 'callStripes')
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 505, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/distribute-0.6.35-py2.7.egg/pkg_resources.py", line 1245, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cLoops-0.91-py2.7.egg/EGG-INFO/scripts/callStripes", line 472, in <module>
    cpus=op.cpu)
  File "/usr/local/lib/python2.7/dist-packages/cLoops-0.91-py2.7.egg/EGG-INFO/scripts/callStripes", line 348, in callStripes
    ds_x = pd.concat(ds_x)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/reshape/concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/reshape/concat.py", line 277, in __init__
    raise ValueError('All objects passed were None')
ValueError: All objects passed were None

**Comment by YaqiangCao** [comment]
Hi Mack,
   Sorry for the bug. Could you please give us some sample of the data you used? Such as the chr21. We will try to tune the parameters for you. We initially tune the parameters for H3K27ac HiChIP, so it may be not suitable for your data. 
   We will try to fix the parameter problem. 
Best,
Yaqiang & Zhaoxiong

**Comment by MackZhang** [comment]
I download CTCF HiChIP data form GEO, and the access number is: GSM2705060,GSM2705061.

**Comment by YaqiangCao** [comment]
Could you please give us the bedpe for the data of chr21. It will take long time for us to download and pre-processing and fix the bug for you.
